poke_homepage:
    path:     /
    defaults: { _controller: QuetzacoaltPokeBundle:Default:index }

poke_fetch_data:
    path: /pokemon/{type}
    defaults:
        _controller: QuetzacoaltPokeBundle:Pokemon:index
        
poke_dl_pokemon:
    path: /pokemon/{type}/download
    defaults:
        _controller: QuetzacoaltPokeBundle:Pokemon:download